"use client";
import AppFooter from "@/components/AppFooter/AppFooter";
import AppHeader from "@/components/AppHeader/AppHeader";
import { Metadata } from "next";
import Link from "next/link";
import { usePathname } from "next/navigation";
import "./globals.css";

const metadata: Metadata = {
  title: {
    default: "Next",
    template: "%s - Next app",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navLinks = [
    {
      id: 1,
      label: "Home",
      href: "/",
    },

    {
      id: 2,
      label: "Blog",
      href: "/blog",
    },

    {
      id: 3,
      label: "Products",
      href: "/products",
    },
  ];
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        <AppHeader />
        {navLinks?.map((link) => {
          let isActive = link.href === pathname;
          return (
            <Link
              href={link.href}
              key={link.id}
              className={`m-2 ${isActive ? "text-red-500 font-bold" : "text-blue-600 "}`}
            >
              {link.label}
            </Link>
          );
        })}
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
